
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Buy", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.43.165:8090/Buy?wsdl")
public class Buy
    extends Service
{

    private final static URL BUY_WSDL_LOCATION;
    private final static WebServiceException BUY_EXCEPTION;
    private final static QName BUY_QNAME = new QName("http://tempuri.org/", "Buy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.43.165:8090/Buy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUY_WSDL_LOCATION = url;
        BUY_EXCEPTION = e;
    }

    public Buy() {
        super(__getWsdlLocation(), BUY_QNAME);
    }

    public Buy(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUY_QNAME, features);
    }

    public Buy(URL wsdlLocation) {
        super(wsdlLocation, BUY_QNAME);
    }

    public Buy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUY_QNAME, features);
    }

    public Buy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Buy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBuy
     */
    @WebEndpoint(name = "BasicHttpBinding_IBuy")
    public IBuy getBasicHttpBindingIBuy() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBuy"), IBuy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBuy
     */
    @WebEndpoint(name = "BasicHttpBinding_IBuy")
    public IBuy getBasicHttpBindingIBuy(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBuy"), IBuy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUY_EXCEPTION!= null) {
            throw BUY_EXCEPTION;
        }
        return BUY_WSDL_LOCATION;
    }

}
