
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.localservices.Result;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBuy", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.BuyObjectFactory.class,
    org.datacontract.schemas._2004._07.localservices.ObjectFactory.class,
    BuyObjectFactory.class
})
public interface IBuy {


    /**
     * 
     * @param codedID
     * @param buyerAccount
     * @param rrn
     * @return
     *     returns org.datacontract.schemas._2004._07.localservices.Result
     */
    @WebMethod(operationName = "BuyItem", action = "http://tempuri.org/IBuy/BuyItem")
    @WebResult(name = "BuyItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BuyItem", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyItem")
    @ResponseWrapper(localName = "BuyItemResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyItemResponse")
    @Action(input = "http://tempuri.org/IBuy/BuyItem", output = "http://tempuri.org/IBuy/BuyItemResponse")
    public Result buyItem(
        @WebParam(name = "buyerAccount", targetNamespace = "http://tempuri.org/")
        String buyerAccount,
        @WebParam(name = "codedID", targetNamespace = "http://tempuri.org/")
        String codedID,
        @WebParam(name = "RRN", targetNamespace = "http://tempuri.org/")
        String rrn);

}
