
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICharge", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ChargeObjectFactory.class,
    ChargeObjectFactory.class
})
public interface ICharge {


    /**
     * 
     * @param accID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddCharge", action = "http://tempuri.org/ICharge/AddCharge")
    @WebResult(name = "AddChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddCharge")
    @ResponseWrapper(localName = "AddChargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddChargeResponse")
    @Action(input = "http://tempuri.org/ICharge/AddCharge", output = "http://tempuri.org/ICharge/AddChargeResponse")
    public Boolean addCharge(
        @WebParam(name = "accID", targetNamespace = "http://tempuri.org/")
        String accID);

}
